import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HeightConstraints, MinesConstraints, WidthConstraints } from './types';
import Range from '../components/Range';

const NewGame: NextPage = () => {
  const [gameConfig, setGameConfig] = useState({
    height: HeightConstraints.Default,
    mines: MinesConstraints.Default,
    width: WidthConstraints.Default,
  });

  const MinesConstraintsMax = gameConfig.width * gameConfig.height - 1;

  const onChange = valueObject => {
    let newConfig = {
      ...gameConfig,
      ...valueObject,
    };

    const newMinesConstraintsMax = newConfig.width * newConfig.height - 1;

    if (newConfig.mines > newMinesConstraintsMax) {
      newConfig.mines = newMinesConstraintsMax;
    }

    setGameConfig(newConfig);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Minesweeper - New game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          New Game
        </h1>

        <Range
          constraints={WidthConstraints}
          id="width"
          label="Width"
          value={gameConfig.width}
          onChange={onChange}
        />
        <Range
          constraints={HeightConstraints}
          id="height"
          label="Height"
          value={gameConfig.height}
          onChange={onChange}
        />
        <Range
          constraints={{...MinesConstraints, Max: MinesConstraintsMax}}
          id="mines"
          label="Mines"
          value={gameConfig.mines}
          onChange={onChange}
        />


        {/* <div>
          <label>Width:</label>
          <input type="range" min={WidthConstraints.Min} max={WidthConstraints.Max} value={gameConfig.width} />
          <span>{gameConfig.width}</span>
        </div>
        <label>Height: </label><input type="range" min={HeightConstraints.Min} max={HeightConstraints.Max} value={gameConfig.height} /></label>
        <label>Mines: </label><input type="range" min={MinesConstraints.Min} max={MinesConstraintsMax} value={gameConfig.mines} /></label> */}
      </main>
    </div>
  );
};

export default NewGame;
